### ISSUE TITLE
Remove db ?

### ISSUE THREAD

**Issue by rgarrigue** [YunoHost/example_ynh#7]
Isn't there any facilities to remove the app's database ?

**Comment by Kloadut** [comment]
Not really.

A good old "DROP DATABASE" ^^

**Comment by opi** [comment]
I want to reopen this issue, or open a similar one in https://github.com/YunoHost/moulinette-yunohost .

As we have `yunohost app initdb`, it could be easy and usefull to have a `yunohost app dropdb`; Remove scripts can be cleaner that way.

**Comment by opi** [comment]
Finally, some work is done to create more "app" helper as bash command.  `yunohost app initdb` will disappear too.
